# Generated by Django 4.1.1 on 2023-08-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizando_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
